default: &default
  adapter: postgresql
  encoding: utf8
  host: db
  username: <%= ENV['POSTGRESS_USERNAME'] %>
  password: <%= ENV['POSTGRESS_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: <%= ENV['POSTGRESS_DB_NAME'] %>

test:
  <<: *default
  database: timeliner_test

production:
  <<: *default
  database:
  username:
  password:
